### ISSUE TITLE
Rename the generated enum field

### ISSUE THREAD

**Issue by Ns2Kracy** [dtolnay/typetag#64]
Trait:
```rust
#[async_trait::async_trait]
#[typetag::serde(tag = "type")]
pub trait DriverTrait {}
```
Impl:
```rust
#[derive(Default, Serialize, Deserialize, Debug, Clone)]
pub struct Websocket {
    host: String,
    port: u16,
}

#[typetag::serde(name = "websocket")]
impl DriverTrait for Websocket {}
```

Config:
```rust
#[derive(Default, Serialize, Deserialize)]
pub struct Config{
    pub driver: Option<Vec<Box<dyn DriverTrait>>>,
}
```

When I trying to write this into a toml file, the output is:
```toml
[[driver]]
type = "websocket"
host = ""
port = 0
```

Is there a way to make the output like this:
```toml
[driver.websocker]
host = ""
port = 0
```
or:
```toml
[[driver]]
[driver.websocker]
host = ""
port = 0
```
